# 基本はgithub.comのリポジトリを指定するだけ
# NeoBundleと同じっすね

# =================
#   vim関連
# =================
# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
    if cmd = dein#util#is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# vimshell.vim
[[plugins]]
repo = 'Shougo/vimshell.vim'

# IDEっぽくするやつ
# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# Unite.vimの拡張
# neomru.vim
[[plugins]]
repo = 'Shougo/neomru.vim'

# C-__でカーソル行をコメントアウト
# tcomment.vim
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ファイルツリーを表示する
# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

# スニペットを使う
# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
# neosnippet-snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# 補完入力をサポート
# neocomplete/neocomplcache
# [[plugins]]
# repo = 'Shougo/neocomplcache.vim'
[[plugins]]
repo = 'Shougo/neocomplete.vim'

# ステータスラインを良い感じするやつ
# lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'

# 同時押しをサポートする
# vim-arpeggio
[[plugins]]
repo = 'kana/vim-arpeggio'

# quickrun.vim
[[plugins]]
repo = 'thinca/vim-quickrun'

# vim-ref.vim
[[plugins]]
repo = 'thinca/vim-ref'

# text-objectを強化するやつ
# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# vim-watchdog
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# shabadou.vim
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# =================
#   Ruby関連
# =================
# Rubyのendを保管する
# vim-endwise
[[plugins]]
repo = 'tpope/vim-endwise'

# Rubyのいろいろ
# vim-ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'

# railsのいろいろ
# vim-rails
[[plugins]]
repo = 'tpope/vim-rails'

# rspec関係
[[plugins]]
repo = 'Keithbsmiley/rspec.vim'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

# slimのなんやかんや
# vim-slim
[[plugins]]
repo = 'slim-template/vim-slim'

# =================
#   Elixir
# =================
# シンタックス、ハイライト等
[[plugins]]
repo = 'elixir-lang/vim-elixir'

# Phoenix対応
[[plugins]]
repo = 'avdgaag/vim-phoenix'

# extest
[[plugins]]
repo = 'BjRo/vim-extest'

# mattreduce/vim-mix
[[plugins]]
repo = 'mattreduce/vim-mix'

# =================
#   JavaScript
#   CoffeeScript
# =================
# mktakuyaのおすすめ
# vim-javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'moll/vim-node'

# JSXに対応する
# vim-jsx
# [[plugins]]
# repo = 'mxw/vim-jsx'

# CoffeeScriptを書くためのサムシング
[[plugins]]
repo = 'kchmck/vim-coffee-script'

# =================
#   HTML
#   CSS
# =================
# HTML5のシンタックスに対応
# html5.vim
[[plugins]]
repo = 'othree/html5.vim'

# 閉じタグを良い感じにアレするやつ
# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'

# CSS3のシンタックスに対応
# vim-css3-syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'

# =================
#   R
# =================
# vim-R-Plugin
# vimをR Studioっぽくするやつ
[[plugins]]
repo = 'vim-scripts/Vim-R-plugin'

# ================
#   Python
# ================
# jedi-vim
[[plugins]]
repo = 'davidhalter/jedi-vim'

# =================
#   Markdown
# =================
# Markdownのためのプラグイン
# vim-markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

# =================
#   Others
# =================
# ブラウザで開く
# open-browser.vim
[[plugins]]
repo = 'tyru/open-browser.vim'

# TOML対応
# toml.vim
[[plugins]]
repo = 'cespare/vim-toml'

