# 基本はgithub.comのリポジトリを指定するだけ
# NeoBundleと同じっすね

# =================
#   システム周り
# =================
# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
    if cmd = dein#util#is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# vimshell.vim
[[plugins]]
repo = 'Shougo/vimshell.vim'

# IDEっぽくするやつ
# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# Unite.vimの拡張
# neomru.vim
[[plugins]]
repo = 'Shougo/neomru.vim'

# C-__でカーソル行をコメントアウト
# tcomment.vim
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ファイルツリーを表示する
# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

# ステータスラインを良い感じするやつ
# lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'

# 同時押しをサポートする
# vim-arpeggio
[[plugins]]
repo = 'kana/vim-arpeggio'

# quickrun.vim
[[plugins]]
repo = 'thinca/vim-quickrun'

# vim-ref.vim
[[plugins]]
repo = 'thinca/vim-ref'

# text-objectを強化するやつ
# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# shabadou.vim
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# 多機能な絞り込み検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ======================
# プログラミングサポート
# ======================
# スニペットを使う
# スニペットによる補完
# NeoSnippetやめようかな...
# SirVer/ultisnips
[[plugins]]
repo = 'SirVer/ultisnips'

# vim-snippets
[[plugins]]
repo = 'honza/vim-snippets'

# 補完入力をサポート
# neocomplete.vim
[[plugins]]
repo = 'Shougo/neocomplete.vim'

# 開いたファイルの構造を表示してくれる
# クラス, メソッド, フィールド等
# 新規ファイルタイプの設定を追加する時は下記参照
# https://github.com/majutsushi/tagbar/wiki
# majutsushi/tagbar
[[plugins]]
repo = 'majutsushi/tagbar'

# 閉じ系を自動で補完してよしなにしてくれる
# Townk/vim-autoclose
#[[plugins]]
#repo = 'Townk/vim-autoclose'

# =================[
#   Git
# =================
# VimとGitを連携する
[[plugins]]
repo = 'tpope/vim-fugitive'

# =================
#   Others
# =================
# TOML対応
# toml.vim
[[plugins]]
repo = 'cespare/vim-toml'

